### ISSUE TITLE
What is backtype.storm.scheduler.Globals?

### ISSUE THREAD

**Issue by smirnp** [jerrypeng/storm-resource-aware-scheduler#1]
Cannot find any Globals either in today storm codes or in resource-aware scheduler codes.

**Comment by jerrypeng** [comment]
I am not sure which class you are referring to.  I don't recall resource-aware scheduler ever having a backtype.storm.scheduler.Globals class

**Comment by smirnp** [comment]
Resolved.

**Comment by healthyjk** [comment]
Hi, smirnp. How did you resolved this problem? I meet the same problem.  @smirnp. Thank you!

**Comment by smirnp** [comment]
Where is no problem with storm 1.0.0+, where backtype namespace is replaced with org.apache.storm. In versions below there is no trivial solution

**Comment by healthyjk** [comment]
OK, thank you for your reply. I will have a try. Thanks again!

**Comment by xunyunliu** [comment]
@smirnp could you please provide more details on how to resolve this problem? I have tried to change the version in pom file to 1.0.1, but it does not work and give me even more error.

**Comment by smirnp** [comment]
See my comment above
